{-# LANGUAGE BangPatterns #-}

import BioCalc
import Data.Time.Clock
import qualified Data.ByteString.Char8 as BS

psba_pro = BS.pack "VPSSNAIGLHFYPIWEAATLDEWLYNGGPYQLVIFHFLIGISAYMGRQWELSYRLGMRPWICVAYSAPVSAAFAVFLVYPFGQGSFSDGMPLGISGTFNFMFVFQAEHNILMHPFHMAGVAGMFGGALFSAMHGSLVTSSLIRETTGLDSQNYGYKFGQEEETYNIVAAHGYFGRLIFQYASFNNSRSLHFFLASWPVICVWLTSMGICTMAFNLNGFNFNQSVVDTSGKVVPTWGDVLNRANL"

psba_arab = BS.pack "MTAILERRESESLWGRFCNWITSTENRLYIGWFGVLMIPTLLTATSVFIIAFIAAPPVDIDGIREPVSGSLLYGNNIISGAIIPTSAAIGLHFYPIWEAASVDEWLYNGGPYELIVLHFLLGVACYMGREWELSFRLGMRPWIAVAYSAPVAAATAVFLIYPIGQGSFSDGMPLGISGTFNFMIVFQAEHNILMHPFHMLGVAGVFGGSLFSAMHGSLVTSSLIRETTENESANEGYRFGQEEETYNIVAAHGYFGRLIFQYASFNNSRSLHFFLAAWPVVGIWFTALGISTMAFNLNGFNFNQSVVDSQGRVINTWADIINRANLGMEVMHERNAHNFPLDLAAVEAPSTNG"

main = do
    start <- getCurrentTime
    let !r = align psba_arab psba_pro
    end <- getCurrentTime
    putStrLn $ "align took " ++ show (diffUTCTime end start)
